//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACSDining.Core.Domains
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class DishQuantity
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        [Required]
        public double Quantity { get; set; }
        //[Key, Column(Order = 3)]
        public int DishTypeID { get; set; }
        //[Key, Column(Order = 2)]
        public int DayOfWeekID { get; set; }
        //[Key, Column(Order = 1)]
        public int MenuForWeekID { get; set; }
       // [Key,Column(Order = 0)]
        public int OrderMenuID { get; set; }

        [JsonIgnore]
        public virtual DishType DishType { get; set; }
        [JsonIgnore]
        public virtual DayOfWeek DayOfWeek { get; set; }
        [JsonIgnore]
        public virtual MenuForWeek MenuForWeek { get; set; }
        [JsonIgnore]
        public virtual OrderMenu OrderMenu { get; set; }
    }
}
