//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel;

namespace ACSDining.Core.Domains
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    
    public partial class MenuForWeek
    {
        [Key]
        [DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)]
        public int ID { get; set; }
        [Required]
        public int WeekNumber { get; set; }
        public double SummaryPrice { get; set; }

        [JsonIgnore]
        public virtual ICollection<MenuForDay> MenuForDay { get; set; }
        [JsonIgnore]
        public virtual ICollection<OrderMenu> Orders { get; set; }
        [JsonIgnore]
        public virtual ICollection<PlannedOrderMenu> PlannedOrderMenus { get; set; }
        [JsonIgnore]
        public virtual Year Year { get; set; }
    }
}
