//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACSDining.Core.Domains
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity;
    using System.Threading.Tasks;

    public  class MenuForDay
    {
        public MenuForDay()
        {
            Dishes = new List<Dish>();
            DayOrderMenus = new List<DayOrderMenu>();
        }

        [Key]
        [DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)]
        public int ID { get; set; }

        public double TotalPrice { get; set; }
        //Пользователь может создать заказ на это меню
        public bool OrderCanBeCreated { get; set; }
        //СуперЮзер может изменить меню на этот день
        public bool DayMenuCanBeChanged { get; set; }

        //Пользователь может изменить заказ на это меню
        public bool OrderCanBeChanged { get; set; }

        [JsonIgnore]
        public virtual ICollection<Dish> Dishes { get; set; }

        [JsonIgnore]
        public virtual WorkingDay WorkingDay { get; set; }

        //public ICollection<PlannedDayOrderMenu> PlannedDayOrderMenus { get; set; }
        public ICollection<DayOrderMenu> DayOrderMenus { get; set; }
    }
}
